//@version=6
strategy(//////////////////////////////////////////////////////////////////////////////
// GENERAL
//////////////////////////////////////////////////////////////////////////////

groupGeneral = "General"

enableStrategy = input.bool(
     true,
     "Enable Strategy",
     group = groupGeneral)

showDebug = input.bool(
     false,
     "Debug Mode",
     group = groupGeneral)

//////////////////////////////////////////////////////////////////////////////
// MODULE ENGINE
//////////////////////////////////////////////////////////////////////////////

groupModule = "Modules"

useBiasEngine      = input.bool(true, "4H Bias", group=groupModule)
useLiquidityEngine = input.bool(true, "PDH / PDL", group=groupModule)
useCRTEngine       = input.bool(true, "CRT Sweep", group=groupModule)
useTurtleSoup      = input.bool(true, "Turtle Soup", group=groupModule)
useMSSEngine       = input.bool(true, "MSS", group=groupModule)
useCISDEngine      = input.bool(true, "CISD", group=groupModule)
useOTEEngine       = input.bool(true, "OTE", group=groupModule)
useFVGEngine       = input.bool(true, "FVG", group=groupModule)
useOBEngine        = input.bool(true, "Order Block", group=groupModule)

//////////////////////////////////////////////////////////////////////////////
// RISK
//////////////////////////////////////////////////////////////////////////////

groupRisk = "Risk"

riskPercent = input.float(
     1.0,
     "Risk %",
     minval = 0.1,
     step = 0.1,
     group = groupRisk)

riskReward = input.float(
     2.0,
     "Risk : Reward",
     minval = 1.0,
     step = 0.5,
     group = groupRisk)

//////////////////////////////////////////////////////////////////////////////
// ALERT
//////////////////////////////////////////////////////////////////////////////

groupAlert = "Alert"

enableAlert = input.bool(
     true,
     "Enable Alert",
     group = groupAlert)

useWebhook = input.bool(
     true,
     "Webhook",
     group = groupAlert)

useTelegram = input.bool(
     false,
     "Telegram",
     group = groupAlert)

telegramChatID = input.string(
     "",
     "Telegram Chat ID",
     group = groupAlert)

plot(close, title="Close")
